spring:
  application:
    name: demo-student-docker

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.126.129:5001/postgres
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
